### ISSUE TITLE
Finde ich heutzutage eine gute Blogparade mit den Tipps für Blog-Anfänger

### ISSUE THREAD

**Issue by AlexL777** [AlexL777/Internetblogger.de#49]
Gibt es derzeit eine solche Blogparade, wo ich Tipps als Blog-Beginner bekommen kann? Sind solche Blogparaden zur Zeit am Laufen oder muss ich da selbst in Google lange stöbern? Jede Antwort wäre sehr hilfreich.

**Comment by AlexL777** [comment]
Solch eine Blogparade findest du bei mir unter https://internetblogger.de/2016/11/blogparade-blogger-tipps-fuer-blogbeginner-mache-mit/ und sie ist erst seit gestern am Start. Mitmachen können alle BloggerInnen aus dem DACH-Raum, eben Deutschland, Schweiz und Österreich. Vielleicht gibt es dortzulande welche Interessenten für diese Blogger-Tipps-Blogparade.

Ich werde es gut verfolgen und dich auf dem Laufenden halten. Auch wird die Promotion dieses mal noch etwas mehr sein als bei den früheren Blogparaden sein. Dabei rechne ich mit der Zeit von ein paar Wochen für die grossartige Blogparaden-Promotion.

**Comment by hushiar** [comment]
![image](https://user-images.githubusercontent.com/29357900/27255097-f932233a-5353-11e7-9b64-4b8a94282173.png)
ich habe soeben Bludit installiert, aber kann ich mich als Admin nicht einlogen obwohl alle Angaben korrekt sind.

**Comment by AlexL777** [comment]
Hi @hushiar 
hast du es versucht, dir die Zugangsdaten nochmals zuschicken zu lassen? Bludit lasse ich auch laufen, aber bisher alles gut damit. Versuche mal bitte mit "Zugangscode zuschicken" und teile mir mit, was dann passiert. Dann schauen wir weiter.

**Comment by hushiar** [comment]
Ja, habe ich versucht. Kam nie eine eMail bei mir an

**Comment by AlexL777** [comment]
Ach ja stimmt, man muss es vorher im Backend einstellen, damit die Mails korrekt versandt werden. So habe ich es in Erinnerung. 

Du kannst es höchstens so versuchen, indem du die Datei `users.php` unter `/bl-content/databases` öffnest. Dort sind deine Login-Daten eingetragen. Das Passwort scheint mir ein MD5-Hash zu sein. Es gibt online zahlreiche Generatoren für MD5-Hashes. Generiere ein neues Passwort, trage dort den Hash ein und versuche, dich einzuloggen.

Hast du das Blog schon komplett eingerichtet und viel gebloggt oder alles noch leer? Kannst als Notlösung neu installieren. Es ist doch ein FlatFile CMS und das geht schnell.

**Comment by hushiar** [comment]
Das habe ich gemacht. Eine Testversion ist unter http://www.netandmore.de/ema/bludit/ installiert. Ich habe mein Password mit Hilfe von MD5-Hash-Generator geändert und um Zugangsdaten gebeten, bis jetzt ist nichts gekommen. In der Regel ist eMail-Versand nur über SMTP zuverlässig sonst kommt man über "reject unverified sender" Spamfilter (wenn eingeschaltet) oder andere Hindernisse nicht durch, aber das System hat nach diese Daten nicht gefragt.

Allerdings war es auch nicht so einfach die Datei users.php unter /bl-content/databases zu überschreiben. Das heißt ich musste zuerst die Besitzrechte (chown) auf meine eigene Ändern und danach wieder auf PHP-User übertragen damit das System funktioniert.

Ich schaue nachher ob etwas gekommen ist.

**Comment by AlexL777** [comment]
Hast du versucht, dich einzuloggen? Dafür haben wir auch die Daten geändert, für den Login-Versuch. Es wird keine Mail ankommen, weisst du, weil es im Backend eingestellt werden muss.

Hm...ich kann bei All-inkl. und mit Filezilla oder Bitvise jede Datei einfach so überschreiben, ohne dass ich CHOWN ändern muss. Hast du Shared Webhosting oder eigenen Rootserver?

Wenn nichts mehr hilft, dann Neu-Installation. Aber bitte nochmals einloggen, denn sonst wissen wir nicht, ob das neue Passwort funktioniert. OK, ich warte dann auf dein Feedback.

**Comment by hushiar** [comment]
eMail ist nicht gekommen und ich verfolge das Thema auch nicht mehr

**Comment by AlexL777** [comment]
Du gibst aber schnell auf. Ehrlich! Setze Bludit doch einmal neu auf und vermutlich liegt es am Unterverzeichnis. Auf einer Subdomain läuft das CMS ohne Probleme. Befasse dich doch ein bisschen mit der Materie. Ich teste seit gut 4 Jahren OpenSource Software und sitze manchmal Wochen an einer Installation.

Soviel Zeit und Freizeit gehören dazu, denn ich will es letztendlich installiert haben. Bludit ist noch das Einfachste. Schaue dir mal OpenProject und Redmine mit Ruby&Rails an. Da sitzt du Wochen dran, wenn du die Zusammenhänge vorher nicht kennst.

Daher bitte mehr Geduld und nimm dir wirklich viel Zeit dafür. Ab und an ist es so, dass es nicht will, wie man möchte. Das kenne ich zu gut bei meinen CMS-Tests!

**Comment by hushiar** [comment]
nein, ich gebe in der Regel nicht so schnell auf allerdings hatte ich mein Zweifel ob ich überhaupt ein Blog brauche. Wie auch immer das System läuft jetzt nachdem ich alles eine "Etage" höher platziert habe funktioniert alles wunderbar (auch mit eMail-Versand).
Vermutlich lag es wirklich an Unterverzeichnis (das ist immer noch Hauptaccount) und aus welchem Grund auch immer hat er sein Pfad zu PHP wohl nicht vollständig gefunden.

**Comment by AlexL777** [comment]
Na, das ist doch mal ein sehr erfreuliches Feedback. Vielen Dank 😄 

Ja, ich denke auch, dass das Unterverzeichnis etwas damit zu tun haben könnte. Aber gut, dass es jetzt bei dir läuft. Bludit als CMS ganz passabel und kann durch allerhand Plugins und tolle Themes erweitert werden. Es spricht Deutsch und du bloggst mit einem Ckeditor als Plugin. 

Wünsche dir viel Spass damit und bei Fragen einfach fragen. Vielleicht kann ich helfen.

**Comment by hushiar** [comment]
Vielen Dank auch an dich Alex für deine Hilfe und Geduld. Als nächstes muß ich mein eigener Theme passend zu netandmore.de erstellen. Muß ich nach passende Vorlagen suchen, dürfte nicht so schwierig sein.

**Comment by AlexL777** [comment]
Immer wieder gerne und wenn ich bei CMS helfen kann, dann tue ich das. OK, dann schaust du dich vielleicht auch in der Bludit-Dokumentation etwas um. Leider liegen mir so keine Erfahrungen bezgl. der Erstellung eines Custom Themes. Anpassungen muss man oft vornehmen. Ich nehme meistens etwas aus dem Bestand, das was mir am meisten zusagt.
